---
- name: Install WordPress, MariaDB, and Nginx
  hosts: localhost
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Mariadb
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mariadb-server
        - python3-pymysql

    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
        enabled: true

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Add PHP repos
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Install PHP 8.0 and extensions
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php8.0 
        - php8.0-cli 
        - php8.0-fpm 
        - php8.0-mysql 
        - php-json 
        - php8.0-opcache 
        - php8.0-mbstring 
        - php8.0-xml 
        - php8.0-gd 
        - php8.0-curl

    - name: chown PHP
      file:
        path:
        owner: root
        group: www-data

    - name: Start php8.0-fpm
      service:
        name: php8.0-fpm
        state: started
        enabled: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Create Wordpress folder
      file:
        path: /var/www/html/trantrunghau.com
        state: directory

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/trantrunghau.com
        remote_src: yes
        owner: www-data
        
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: true